services:
  db:
    image: postgres
    container_name: postgres_db_container
    restart: always
    ports:
      - "54421:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

volumes:
  postgres_db_data: